name: RRR Gallery
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.0
  supabase_flutter: ^2.8.4
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^9.0.0
  http: ^0.13.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.0.0
  shared_preferences: ^2.5.2
  crypto: ^3.0.1
  crypt: ^4.2.1
  bcrypt: ^1.0.0
  path: ^1.8.3
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/RRR Logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/rm_gallery.png
    - assets/images/RRR Logo.png