const String supabaseUrl = 'https://smgsbvoyhczishecyoyp.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZ3Nidm95aGN6aXNoZWN5b3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMzg3ODAsImV4cCI6MjA1NTYxNDc4MH0.5-xTaSqWwjSGozkuRJVfVl1ZWr2ZtejgB5JFmjb2CjQ';
